# Generated by Django 3.1.6 on 2021-02-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('posicao', models.IntegerField(verbose_name='Posicao')),
                ('status', models.CharField(
                    max_length=30, null=True, verbose_name='Status')),
                ('curso', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
    ]
